// <auto-generated />
using System;
using F1Fast.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace F1Fast.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260320175756_AddLembreteEnviadoToEtapa")]
    partial class AddLembreteEnviadoToEtapa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("F1Fast.API.Models.Equipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Equipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cor = "#FF8000",
                            Nome = "McLaren"
                        },
                        new
                        {
                            Id = 2,
                            Cor = "#3671C6",
                            Nome = "Red Bull"
                        },
                        new
                        {
                            Id = 3,
                            Cor = "#27F4D2",
                            Nome = "Mercedes"
                        },
                        new
                        {
                            Id = 4,
                            Cor = "#E8002D",
                            Nome = "Ferrari"
                        },
                        new
                        {
                            Id = 5,
                            Cor = "#358C75",
                            Nome = "Aston Martin"
                        },
                        new
                        {
                            Id = 6,
                            Cor = "#64C4FF",
                            Nome = "Williams"
                        },
                        new
                        {
                            Id = 7,
                            Cor = "#FF87BC",
                            Nome = "Alpine"
                        },
                        new
                        {
                            Id = 8,
                            Cor = "#BDB246",
                            Nome = "Audi"
                        },
                        new
                        {
                            Id = 9,
                            Cor = "#B0B0B0",
                            Nome = "Haas"
                        },
                        new
                        {
                            Id = 10,
                            Cor = "#6692FF",
                            Nome = "Racing Bulls"
                        },
                        new
                        {
                            Id = 11,
                            Cor = "#999999",
                            Nome = "Cadillac"
                        });
                });

            modelBuilder.Entity("F1Fast.API.Models.Etapa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Circuito")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("DataCorrida")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Encerrada")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LembreteEnviado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("PrazoQualify")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Sprint")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Etapas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cidade = "Melbourne",
                            Circuito = "Albert Park",
                            DataCorrida = new DateTime(2026, 3, 8, 1, 0, 0, 0, DateTimeKind.Utc),
                            Encerrada = false,
                            LembreteEnviado = false,
                            Nome = "GP da Austrália",
                            Numero = 1,
                            Pais = "🇦🇺",
                            PrazoQualify = new DateTime(2026, 3, 7, 2, 0, 0, 0, DateTimeKind.Utc),
                            Sprint = false
                        },
                        new
                        {
                            Id = 2,
                            Cidade = "Changai",
                            Circuito = "Changai",
                            DataCorrida = new DateTime(2026, 3, 13, 4, 30, 0, 0, DateTimeKind.Utc),
                            Encerrada = false,
                            LembreteEnviado = false,
                            Nome = "Sprint da China",
                            Numero = 2,
                            Pais = "🇨🇳",
                            PrazoQualify = new DateTime(2026, 3, 13, 4, 30, 0, 0, DateTimeKind.Utc),
                            Sprint = true
                        },
                        new
                        {
                            Id = 3,
                            Cidade = "Changai",
                            Circuito = "Changai",
                            DataCorrida = new DateTime(2026, 3, 14, 4, 0, 0, 0, DateTimeKind.Utc),
                            Encerrada = false,
                            LembreteEnviado = false,
                            Nome = "GP da China",
                            Numero = 3,
                            Pais = "🇨🇳",
                            PrazoQualify = new DateTime(2026, 3, 14, 4, 0, 0, 0, DateTimeKind.Utc),
                            Sprint = false
                        },
                        new
                        {
                            Id = 4,
                            Cidade = "Suzuka",
                            Circuito = "Suzuka",
                            DataCorrida = new DateTime(2026, 3, 28, 3, 0, 0, 0, DateTimeKind.Utc),
                            Encerrada = false,
                            LembreteEnviado = false,
                            Nome = "GP do Japão",
                            Numero = 4,
                            Pais = "🇯🇵",
                            PrazoQualify = new DateTime(2026, 3, 28, 3, 0, 0, 0, DateTimeKind.Utc),
                            Sprint = false
                        },
                        new
                        {
                            Id = 5,
                            Cidade = "Sakhir",
                            Circuito = "Sakhir",
                            DataCorrida = new DateTime(2026, 4, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Encerrada = false,
                            LembreteEnviado = false,
                            Nome = "GP do Bahrein",
                            Numero = 5,
                            Pais = "🇧🇭",
                            PrazoQualify = new DateTime(2026, 4, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Sprint = false
                        },
                        new
                        {
                            Id = 6,
                            Cidade = "Jeddah",
                            Circuito = "Jeddah",
                            DataCorrida = new DateTime(2026, 4, 18, 14, 0, 0, 0, DateTimeKind.Utc),
                            Encerrada = false,
                            LembreteEnviado = false,
                            Nome = "GP da Arábia Saudita",
                            Numero = 6,
                            Pais = "🇸🇦",
                            PrazoQualify = new DateTime(2026, 4, 18, 14, 0, 0, 0, DateTimeKind.Utc),
                            Sprint = false
                        },
                        new
                        {
                            Id = 7,
                            Cidade = "Miami",
                            Circuito = "Miami",
                            DataCorrida = new DateTime(2026, 5, 1, 17, 30, 0, 0, DateTimeKind.Utc),
                            Encerrada = false,
                            LembreteEnviado = false,
                            Nome = "Sprint de Miami",
                            Numero = 7,
                            Pais = "🇺🇸",
                            PrazoQualify = new DateTime(2026, 5, 1, 17, 30, 0, 0, DateTimeKind.Utc),
                            Sprint = true
                        },
                        new
                        {
                            Id = 8,
                            Cidade = "Miami",
                            Circuito = "Miami",
                            DataCorrida = new DateTime(2026, 5, 2, 17, 0, 0, 0, DateTimeKind.Utc),
                            Encerrada = false,
                            LembreteEnviado = false,
                            Nome = "GP de Miami",
                            Numero = 8,
                            Pais = "🇺🇸",
                            PrazoQualify = new DateTime(2026, 5, 2, 17, 0, 0, 0, DateTimeKind.Utc),
                            Sprint = false
                        },
                        new
                        {
                            Id = 9,
                            Cidade = "Montreal",
                            Circuito = "Montreal",
                            DataCorrida = new DateTime(2026, 5, 22, 17, 30, 0, 0, DateTimeKind.Utc),
                            Encerrada = false,
                            LembreteEnviado = false,
                            Nome = "Sprint do Canadá",
                            Numero = 9,
                            Pais = "🇨🇦",
                            PrazoQualify = new DateTime(2026, 5, 22, 17, 30, 0, 0, DateTimeKind.Utc),
                            Sprint = true
                        },
                        new
                        {
                            Id = 10,
                            Cidade = "Montreal",
                            Circuito = "Montreal",
                            DataCorrida = new DateTime(2026, 5, 23, 17, 0, 0, 0, DateTimeKind.Utc),
                            Encerrada = false,
                            LembreteEnviado = false,
                            Nome = "GP do Canadá",
                            Numero = 10,
                            Pais = "🇨🇦",
                            PrazoQualify = new DateTime(2026, 5, 23, 17, 0, 0, 0, DateTimeKind.Utc),
                            Sprint = false
                        },
                        new
                        {
                            Id = 11,
                            Cidade = "Monte Carlo",
                            Circuito = "Monte Carlo",
                            DataCorrida = new DateTime(2026, 6, 6, 11, 0, 0, 0, DateTimeKind.Utc),
                            Encerrada = false,
                            LembreteEnviado = false,
                            Nome = "GP de Mônaco",
                            Numero = 11,
                            Pais = "🇲🇨",
                            PrazoQualify = new DateTime(2026, 6, 6, 11, 0, 0, 0, DateTimeKind.Utc),
                            Sprint = false
                        },
                        new
                        {
                            Id = 12,
                            Cidade = "Barcelona",
                            Circuito = "Catalunia",
                            DataCorrida = new DateTime(2026, 6, 13, 11, 0, 0, 0, DateTimeKind.Utc),
                            Encerrada = false,
                            LembreteEnviado = false,
                            Nome = "GP de Barcelona",
                            Numero = 12,
                            Pais = "🇪🇸",
                            PrazoQualify = new DateTime(2026, 6, 13, 11, 0, 0, 0, DateTimeKind.Utc),
                            Sprint = false
                        },
                        new
                        {
                            Id = 13,
                            Cidade = "Spielberg",
                            Circuito = "Red Bull Ring",
                            DataCorrida = new DateTime(2026, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Encerrada = false,
                            LembreteEnviado = false,
                            Nome = "GP da Áustria",
                            Numero = 13,
                            Pais = "🇦🇹",
                            PrazoQualify = new DateTime(2026, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Sprint = false
                        },
                        new
                        {
                            Id = 14,
                            Cidade = "Silverstone",
                            Circuito = "Silverstone",
                            DataCorrida = new DateTime(2026, 7, 3, 12, 30, 0, 0, DateTimeKind.Utc),
                            Encerrada = false,
                            LembreteEnviado = false,
                            Nome = "Sprint da Grã-Bretanha",
                            Numero = 14,
                            Pais = "🇬🇧",
                            PrazoQualify = new DateTime(2026, 7, 3, 12, 30, 0, 0, DateTimeKind.Utc),
                            Sprint = true
                        },
                        new
                        {
                            Id = 15,
                            Cidade = "Silverstone",
                            Circuito = "Silverstone",
                            DataCorrida = new DateTime(2026, 7, 4, 12, 0, 0, 0, DateTimeKind.Utc),
                            Encerrada = false,
                            LembreteEnviado = false,
                            Nome = "GP da Grã-Bretanha",
                            Numero = 15,
                            Pais = "🇬🇧",
                            PrazoQualify = new DateTime(2026, 7, 4, 12, 0, 0, 0, DateTimeKind.Utc),
                            Sprint = false
                        },
                        new
                        {
                            Id = 16,
                            Cidade = "Spa",
                            Circuito = "Spa-Francorchamps",
                            DataCorrida = new DateTime(2026, 7, 18, 11, 0, 0, 0, DateTimeKind.Utc),
                            Encerrada = false,
                            LembreteEnviado = false,
                            Nome = "GP da Bélgica",
                            Numero = 16,
                            Pais = "🇧🇪",
                            PrazoQualify = new DateTime(2026, 7, 18, 11, 0, 0, 0, DateTimeKind.Utc),
                            Sprint = false
                        },
                        new
                        {
                            Id = 17,
                            Cidade = "Budapest",
                            Circuito = "Hungaroring",
                            DataCorrida = new DateTime(2026, 7, 25, 11, 0, 0, 0, DateTimeKind.Utc),
                            Encerrada = false,
                            LembreteEnviado = false,
                            Nome = "GP da Hungria",
                            Numero = 17,
                            Pais = "🇭🇺",
                            PrazoQualify = new DateTime(2026, 7, 25, 11, 0, 0, 0, DateTimeKind.Utc),
                            Sprint = false
                        },
                        new
                        {
                            Id = 18,
                            Cidade = "Zandvoort",
                            Circuito = "Zandvoort",
                            DataCorrida = new DateTime(2026, 8, 21, 11, 30, 0, 0, DateTimeKind.Utc),
                            Encerrada = false,
                            LembreteEnviado = false,
                            Nome = "Sprint da Holanda",
                            Numero = 18,
                            Pais = "🇳🇱",
                            PrazoQualify = new DateTime(2026, 8, 21, 11, 30, 0, 0, DateTimeKind.Utc),
                            Sprint = true
                        },
                        new
                        {
                            Id = 19,
                            Cidade = "Zandvoort",
                            Circuito = "Zandvoort",
                            DataCorrida = new DateTime(2026, 8, 22, 11, 0, 0, 0, DateTimeKind.Utc),
                            Encerrada = false,
                            LembreteEnviado = false,
                            Nome = "GP da Holanda",
                            Numero = 19,
                            Pais = "🇳🇱",
                            PrazoQualify = new DateTime(2026, 8, 22, 11, 0, 0, 0, DateTimeKind.Utc),
                            Sprint = false
                        },
                        new
                        {
                            Id = 20,
                            Cidade = "Monza",
                            Circuito = "Monza",
                            DataCorrida = new DateTime(2026, 9, 5, 11, 0, 0, 0, DateTimeKind.Utc),
                            Encerrada = false,
                            LembreteEnviado = false,
                            Nome = "GP da Itália",
                            Numero = 20,
                            Pais = "🇮🇹",
                            PrazoQualify = new DateTime(2026, 9, 5, 11, 0, 0, 0, DateTimeKind.Utc),
                            Sprint = false
                        },
                        new
                        {
                            Id = 21,
                            Cidade = "Madri",
                            Circuito = "Madri",
                            DataCorrida = new DateTime(2026, 9, 12, 11, 0, 0, 0, DateTimeKind.Utc),
                            Encerrada = false,
                            LembreteEnviado = false,
                            Nome = "GP da Espanha",
                            Numero = 21,
                            Pais = "🇪🇸",
                            PrazoQualify = new DateTime(2026, 9, 12, 11, 0, 0, 0, DateTimeKind.Utc),
                            Sprint = false
                        },
                        new
                        {
                            Id = 22,
                            Cidade = "Baku",
                            Circuito = "Baku",
                            DataCorrida = new DateTime(2026, 9, 25, 9, 0, 0, 0, DateTimeKind.Utc),
                            Encerrada = false,
                            LembreteEnviado = false,
                            Nome = "GP do Azerbaijão",
                            Numero = 22,
                            Pais = "🇦🇿",
                            PrazoQualify = new DateTime(2026, 9, 25, 9, 0, 0, 0, DateTimeKind.Utc),
                            Sprint = false
                        },
                        new
                        {
                            Id = 23,
                            Cidade = "Singapura",
                            Circuito = "Marina Bay",
                            DataCorrida = new DateTime(2026, 10, 9, 9, 30, 0, 0, DateTimeKind.Utc),
                            Encerrada = false,
                            LembreteEnviado = false,
                            Nome = "Sprint de Singapura",
                            Numero = 23,
                            Pais = "🇸🇬",
                            PrazoQualify = new DateTime(2026, 10, 9, 9, 30, 0, 0, DateTimeKind.Utc),
                            Sprint = true
                        },
                        new
                        {
                            Id = 24,
                            Cidade = "Singapura",
                            Circuito = "Marina Bay",
                            DataCorrida = new DateTime(2026, 10, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            Encerrada = false,
                            LembreteEnviado = false,
                            Nome = "GP de Singapura",
                            Numero = 24,
                            Pais = "🇸🇬",
                            PrazoQualify = new DateTime(2026, 10, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            Sprint = false
                        },
                        new
                        {
                            Id = 25,
                            Cidade = "Austin",
                            Circuito = "Austin",
                            DataCorrida = new DateTime(2026, 10, 24, 18, 0, 0, 0, DateTimeKind.Utc),
                            Encerrada = false,
                            LembreteEnviado = false,
                            Nome = "GP dos EUA",
                            Numero = 25,
                            Pais = "🇺🇸",
                            PrazoQualify = new DateTime(2026, 10, 24, 18, 0, 0, 0, DateTimeKind.Utc),
                            Sprint = false
                        },
                        new
                        {
                            Id = 26,
                            Cidade = "Cidade do México",
                            Circuito = "Cidade do México",
                            DataCorrida = new DateTime(2026, 10, 31, 18, 0, 0, 0, DateTimeKind.Utc),
                            Encerrada = false,
                            LembreteEnviado = false,
                            Nome = "GP do México",
                            Numero = 26,
                            Pais = "🇲🇽",
                            PrazoQualify = new DateTime(2026, 10, 31, 18, 0, 0, 0, DateTimeKind.Utc),
                            Sprint = false
                        },
                        new
                        {
                            Id = 27,
                            Cidade = "São Paulo",
                            Circuito = "Interlagos",
                            DataCorrida = new DateTime(2026, 11, 7, 15, 0, 0, 0, DateTimeKind.Utc),
                            Encerrada = false,
                            LembreteEnviado = false,
                            Nome = "GP do Brasil",
                            Numero = 27,
                            Pais = "🇧🇷",
                            PrazoQualify = new DateTime(2026, 11, 7, 15, 0, 0, 0, DateTimeKind.Utc),
                            Sprint = false
                        },
                        new
                        {
                            Id = 28,
                            Cidade = "Las Vegas",
                            Circuito = "Las Vegas",
                            DataCorrida = new DateTime(2026, 11, 21, 1, 0, 0, 0, DateTimeKind.Utc),
                            Encerrada = false,
                            LembreteEnviado = false,
                            Nome = "GP de Las Vegas",
                            Numero = 28,
                            Pais = "🇺🇸",
                            PrazoQualify = new DateTime(2026, 11, 21, 1, 0, 0, 0, DateTimeKind.Utc),
                            Sprint = false
                        },
                        new
                        {
                            Id = 29,
                            Cidade = "Lusail",
                            Circuito = "Lusail",
                            DataCorrida = new DateTime(2026, 11, 28, 15, 0, 0, 0, DateTimeKind.Utc),
                            Encerrada = false,
                            LembreteEnviado = false,
                            Nome = "GP do Catar",
                            Numero = 29,
                            Pais = "🇶🇦",
                            PrazoQualify = new DateTime(2026, 11, 28, 15, 0, 0, 0, DateTimeKind.Utc),
                            Sprint = false
                        },
                        new
                        {
                            Id = 30,
                            Cidade = "Abu Dhabi",
                            Circuito = "Yas Marina",
                            DataCorrida = new DateTime(2026, 12, 5, 11, 0, 0, 0, DateTimeKind.Utc),
                            Encerrada = false,
                            LembreteEnviado = false,
                            Nome = "GP de Abu Dhabi",
                            Numero = 30,
                            Pais = "🇦🇪",
                            PrazoQualify = new DateTime(2026, 12, 5, 11, 0, 0, 0, DateTimeKind.Utc),
                            Sprint = false
                        });
                });

            modelBuilder.Entity("F1Fast.API.Models.Palpite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("EnviadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EtapaId")
                        .HasColumnType("int");

                    b.Property<int>("MelhorVoltaId")
                        .HasColumnType("int");

                    b.Property<int>("PoleId")
                        .HasColumnType("int");

                    b.Property<int?>("PontosObtidos")
                        .HasColumnType("int");

                    b.Property<int>("Pos10Id")
                        .HasColumnType("int");

                    b.Property<int>("Pos1Id")
                        .HasColumnType("int");

                    b.Property<int>("Pos2Id")
                        .HasColumnType("int");

                    b.Property<int>("Pos3Id")
                        .HasColumnType("int");

                    b.Property<int>("Pos4Id")
                        .HasColumnType("int");

                    b.Property<int>("Pos5Id")
                        .HasColumnType("int");

                    b.Property<int>("Pos6Id")
                        .HasColumnType("int");

                    b.Property<int>("Pos7Id")
                        .HasColumnType("int");

                    b.Property<int>("Pos8Id")
                        .HasColumnType("int");

                    b.Property<int>("Pos9Id")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EtapaId");

                    b.HasIndex("UsuarioId", "EtapaId")
                        .IsUnique();

                    b.ToTable("Palpites");
                });

            modelBuilder.Entity("F1Fast.API.Models.Piloto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("EquipeId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipeId");

                    b.ToTable("Pilotos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            EquipeId = 1,
                            Nome = "Lando Norris",
                            Numero = 1
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            EquipeId = 2,
                            Nome = "Max Verstappen",
                            Numero = 3
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            EquipeId = 8,
                            Nome = "Gabriel Bortoleto",
                            Numero = 5
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            EquipeId = 2,
                            Nome = "Isack Hadjar",
                            Numero = 6
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            EquipeId = 7,
                            Nome = "Pierre Gasly",
                            Numero = 10
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            EquipeId = 11,
                            Nome = "Sergio Perez",
                            Numero = 11
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            EquipeId = 3,
                            Nome = "Kimi Antonelli",
                            Numero = 12
                        },
                        new
                        {
                            Id = 8,
                            Ativo = true,
                            EquipeId = 5,
                            Nome = "Fernando Alonso",
                            Numero = 14
                        },
                        new
                        {
                            Id = 9,
                            Ativo = true,
                            EquipeId = 4,
                            Nome = "Charles Leclerc",
                            Numero = 16
                        },
                        new
                        {
                            Id = 10,
                            Ativo = true,
                            EquipeId = 5,
                            Nome = "Lance Stroll",
                            Numero = 18
                        },
                        new
                        {
                            Id = 11,
                            Ativo = true,
                            EquipeId = 6,
                            Nome = "Alexander Albon",
                            Numero = 23
                        },
                        new
                        {
                            Id = 12,
                            Ativo = true,
                            EquipeId = 8,
                            Nome = "Nico Hülkenberg",
                            Numero = 27
                        },
                        new
                        {
                            Id = 13,
                            Ativo = true,
                            EquipeId = 10,
                            Nome = "Liam Lawson",
                            Numero = 30
                        },
                        new
                        {
                            Id = 14,
                            Ativo = true,
                            EquipeId = 9,
                            Nome = "Esteban Ocon",
                            Numero = 31
                        },
                        new
                        {
                            Id = 15,
                            Ativo = true,
                            EquipeId = 10,
                            Nome = "Arvid Lindblad",
                            Numero = 41
                        },
                        new
                        {
                            Id = 16,
                            Ativo = true,
                            EquipeId = 7,
                            Nome = "Franco Colapinto",
                            Numero = 43
                        },
                        new
                        {
                            Id = 17,
                            Ativo = true,
                            EquipeId = 4,
                            Nome = "Lewis Hamilton",
                            Numero = 44
                        },
                        new
                        {
                            Id = 18,
                            Ativo = true,
                            EquipeId = 6,
                            Nome = "Carlos Sainz",
                            Numero = 55
                        },
                        new
                        {
                            Id = 19,
                            Ativo = true,
                            EquipeId = 3,
                            Nome = "George Russell",
                            Numero = 63
                        },
                        new
                        {
                            Id = 20,
                            Ativo = true,
                            EquipeId = 11,
                            Nome = "Valtteri Bottas",
                            Numero = 77
                        },
                        new
                        {
                            Id = 21,
                            Ativo = true,
                            EquipeId = 1,
                            Nome = "Oscar Piastri",
                            Numero = 81
                        },
                        new
                        {
                            Id = 22,
                            Ativo = true,
                            EquipeId = 9,
                            Nome = "Oliver Bearman",
                            Numero = 87
                        });
                });

            modelBuilder.Entity("F1Fast.API.Models.Pontuacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AcertosExatos")
                        .HasColumnType("int");

                    b.Property<int>("AcertosPiloto")
                        .HasColumnType("int");

                    b.Property<int>("AcertosUmaPos")
                        .HasColumnType("int");

                    b.Property<bool>("AcertouMelhorVolta")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AcertouPole")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("EtapaId")
                        .HasColumnType("int");

                    b.Property<int>("Pontos")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EtapaId");

                    b.HasIndex("UsuarioId", "EtapaId")
                        .IsUnique();

                    b.ToTable("Pontuacoes");
                });

            modelBuilder.Entity("F1Fast.API.Models.Resultado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("EtapaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InseridoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MelhorVoltaId")
                        .HasColumnType("int");

                    b.Property<int>("PoleId")
                        .HasColumnType("int");

                    b.Property<int>("Pos10Id")
                        .HasColumnType("int");

                    b.Property<int>("Pos11Id")
                        .HasColumnType("int");

                    b.Property<int>("Pos1Id")
                        .HasColumnType("int");

                    b.Property<int>("Pos2Id")
                        .HasColumnType("int");

                    b.Property<int>("Pos3Id")
                        .HasColumnType("int");

                    b.Property<int>("Pos4Id")
                        .HasColumnType("int");

                    b.Property<int>("Pos5Id")
                        .HasColumnType("int");

                    b.Property<int>("Pos6Id")
                        .HasColumnType("int");

                    b.Property<int>("Pos7Id")
                        .HasColumnType("int");

                    b.Property<int>("Pos8Id")
                        .HasColumnType("int");

                    b.Property<int>("Pos9Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EtapaId")
                        .IsUnique();

                    b.ToTable("Resultados");
                });

            modelBuilder.Entity("F1Fast.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ResetToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("F1Fast.API.Models.Palpite", b =>
                {
                    b.HasOne("F1Fast.API.Models.Etapa", "Etapa")
                        .WithMany("Palpites")
                        .HasForeignKey("EtapaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("F1Fast.API.Models.Usuario", "Usuario")
                        .WithMany("Palpites")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etapa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("F1Fast.API.Models.Piloto", b =>
                {
                    b.HasOne("F1Fast.API.Models.Equipe", "Equipe")
                        .WithMany("Pilotos")
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipe");
                });

            modelBuilder.Entity("F1Fast.API.Models.Pontuacao", b =>
                {
                    b.HasOne("F1Fast.API.Models.Etapa", "Etapa")
                        .WithMany()
                        .HasForeignKey("EtapaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("F1Fast.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etapa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("F1Fast.API.Models.Resultado", b =>
                {
                    b.HasOne("F1Fast.API.Models.Etapa", "Etapa")
                        .WithOne("Resultado")
                        .HasForeignKey("F1Fast.API.Models.Resultado", "EtapaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etapa");
                });

            modelBuilder.Entity("F1Fast.API.Models.Equipe", b =>
                {
                    b.Navigation("Pilotos");
                });

            modelBuilder.Entity("F1Fast.API.Models.Etapa", b =>
                {
                    b.Navigation("Palpites");

                    b.Navigation("Resultado");
                });

            modelBuilder.Entity("F1Fast.API.Models.Usuario", b =>
                {
                    b.Navigation("Palpites");
                });
#pragma warning restore 612, 618
        }
    }
}
