// <auto-generated />
using System;
using F1Fast.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace F1Fast.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260320201256_AddSessoesECircuitoSvg")]
    partial class AddSessoesECircuitoSvg
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("F1Fast.API.Models.Equipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Equipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cor = "#FF8000",
                            Nome = "McLaren"
                        },
                        new
                        {
                            Id = 2,
                            Cor = "#3671C6",
                            Nome = "Red Bull"
                        },
                        new
                        {
                            Id = 3,
                            Cor = "#27F4D2",
                            Nome = "Mercedes"
                        },
                        new
                        {
                            Id = 4,
                            Cor = "#E8002D",
                            Nome = "Ferrari"
                        },
                        new
                        {
                            Id = 5,
                            Cor = "#358C75",
                            Nome = "Aston Martin"
                        },
                        new
                        {
                            Id = 6,
                            Cor = "#64C4FF",
                            Nome = "Williams"
                        },
                        new
                        {
                            Id = 7,
                            Cor = "#FF87BC",
                            Nome = "Alpine"
                        },
                        new
                        {
                            Id = 8,
                            Cor = "#BDB246",
                            Nome = "Audi"
                        },
                        new
                        {
                            Id = 9,
                            Cor = "#B0B0B0",
                            Nome = "Haas"
                        },
                        new
                        {
                            Id = 10,
                            Cor = "#6692FF",
                            Nome = "Racing Bulls"
                        },
                        new
                        {
                            Id = 11,
                            Cor = "#999999",
                            Nome = "Cadillac"
                        });
                });

            modelBuilder.Entity("F1Fast.API.Models.Etapa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AnoRecord")
                        .HasColumnType("int");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Circuito")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CircuitoComprimento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CircuitoSvg")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CircuitoTipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("Classificacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataCorrida")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Distancia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("Encerrada")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LembreteEnviado")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LembreteUrgenteEnviado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("PrazoQualify")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Recordista")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("Sprint")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TempoRecord")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("TreinoLivre1")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("TreinoLivre2")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("TreinoLivre3")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Voltas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Etapas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnoRecord = 2022,
                            Cidade = "Melbourne",
                            Circuito = "Albert Park",
                            CircuitoComprimento = "5.278 km",
                            CircuitoSvg = "<svg viewBox=\"0 0 300 200\" fill=\"none\"><path d=\"M50 160 Q30 140 30 100 Q30 50 60 30 Q90 10 140 15 L200 20 Q240 25 260 50 Q280 80 270 120 Q260 150 230 165 L180 175 Q160 170 150 155 Q140 140 130 145 L100 160 Z\" stroke=\"white\" stroke-width=\"8\" stroke-linejoin=\"round\" stroke-linecap=\"round\"/><circle cx=\"50\" cy=\"160\" r=\"6\" fill=\"#E8001A\"/></svg>",
                            CircuitoTipo = "Circuito semi-permanente",
                            Classificacao = new DateTime(2026, 3, 7, 5, 0, 0, 0, DateTimeKind.Utc),
                            DataCorrida = new DateTime(2026, 3, 8, 1, 0, 0, 0, DateTimeKind.Utc),
                            Distancia = "306.1 km",
                            Encerrada = false,
                            LembreteEnviado = false,
                            LembreteUrgenteEnviado = false,
                            Nome = "GP da Austrália",
                            Numero = 1,
                            Pais = "🇦🇺",
                            PrazoQualify = new DateTime(2026, 3, 7, 2, 0, 0, 0, DateTimeKind.Utc),
                            Recordista = "Charles Leclerc",
                            Sprint = false,
                            TempoRecord = "1:19.813",
                            TreinoLivre1 = new DateTime(2026, 3, 6, 1, 30, 0, 0, DateTimeKind.Utc),
                            TreinoLivre2 = new DateTime(2026, 3, 6, 5, 0, 0, 0, DateTimeKind.Utc),
                            TreinoLivre3 = new DateTime(2026, 3, 7, 1, 30, 0, 0, DateTimeKind.Utc),
                            Voltas = 58
                        },
                        new
                        {
                            Id = 2,
                            AnoRecord = 2004,
                            Cidade = "Changai",
                            Circuito = "Changai",
                            CircuitoComprimento = "5.451 km",
                            CircuitoSvg = "<svg viewBox=\"0 0 300 200\" fill=\"none\"><path d=\"M40 180 L40 100 Q40 60 70 40 L130 20 Q160 10 180 30 Q200 50 180 70 Q160 90 180 110 Q200 130 240 120 L270 100 Q290 80 280 50 L270 30 Q260 20 240 25 L200 40\" stroke=\"white\" stroke-width=\"8\" stroke-linejoin=\"round\" stroke-linecap=\"round\"/><circle cx=\"40\" cy=\"180\" r=\"6\" fill=\"#E8001A\"/></svg>",
                            CircuitoTipo = "Circuito permanente",
                            Classificacao = new DateTime(2026, 3, 12, 8, 30, 0, 0, DateTimeKind.Utc),
                            DataCorrida = new DateTime(2026, 3, 13, 4, 30, 0, 0, DateTimeKind.Utc),
                            Distancia = "103.6 km",
                            Encerrada = false,
                            LembreteEnviado = false,
                            LembreteUrgenteEnviado = false,
                            Nome = "Sprint da China",
                            Numero = 2,
                            Pais = "🇨🇳",
                            PrazoQualify = new DateTime(2026, 3, 13, 4, 30, 0, 0, DateTimeKind.Utc),
                            Recordista = "Michael Schumacher",
                            Sprint = true,
                            TempoRecord = "1:32.238",
                            TreinoLivre1 = new DateTime(2026, 3, 12, 5, 0, 0, 0, DateTimeKind.Utc),
                            Voltas = 19
                        },
                        new
                        {
                            Id = 3,
                            AnoRecord = 2004,
                            Cidade = "Changai",
                            Circuito = "Changai",
                            CircuitoComprimento = "5.451 km",
                            CircuitoSvg = "<svg viewBox=\"0 0 300 200\" fill=\"none\"><path d=\"M40 180 L40 100 Q40 60 70 40 L130 20 Q160 10 180 30 Q200 50 180 70 Q160 90 180 110 Q200 130 240 120 L270 100 Q290 80 280 50 L270 30 Q260 20 240 25 L200 40\" stroke=\"white\" stroke-width=\"8\" stroke-linejoin=\"round\" stroke-linecap=\"round\"/><circle cx=\"40\" cy=\"180\" r=\"6\" fill=\"#E8001A\"/></svg>",
                            CircuitoTipo = "Circuito permanente",
                            Classificacao = new DateTime(2026, 3, 13, 8, 30, 0, 0, DateTimeKind.Utc),
                            DataCorrida = new DateTime(2026, 3, 14, 4, 0, 0, 0, DateTimeKind.Utc),
                            Distancia = "305.1 km",
                            Encerrada = false,
                            LembreteEnviado = false,
                            LembreteUrgenteEnviado = false,
                            Nome = "GP da China",
                            Numero = 3,
                            Pais = "🇨🇳",
                            PrazoQualify = new DateTime(2026, 3, 14, 4, 0, 0, 0, DateTimeKind.Utc),
                            Recordista = "Michael Schumacher",
                            Sprint = false,
                            TempoRecord = "1:32.238",
                            Voltas = 56
                        },
                        new
                        {
                            Id = 4,
                            AnoRecord = 2019,
                            Cidade = "Suzuka",
                            Circuito = "Suzuka",
                            CircuitoComprimento = "5.807 km",
                            CircuitoSvg = "<svg viewBox=\"0 0 300 200\" fill=\"none\"><path d=\"M60 170 Q30 150 20 120 Q10 80 40 50 Q70 20 120 20 L180 25 Q220 30 240 60 Q250 80 230 100 Q210 115 220 135 Q230 155 210 170 Q180 190 140 180 Q100 170 80 140 Q65 120 80 100 Q100 80 130 90 Q150 100 140 120\" stroke=\"white\" stroke-width=\"8\" stroke-linejoin=\"round\" stroke-linecap=\"round\"/><circle cx=\"60\" cy=\"170\" r=\"6\" fill=\"#E8001A\"/></svg>",
                            CircuitoTipo = "Circuito permanente",
                            Classificacao = new DateTime(2026, 3, 27, 7, 0, 0, 0, DateTimeKind.Utc),
                            DataCorrida = new DateTime(2026, 3, 28, 3, 0, 0, 0, DateTimeKind.Utc),
                            Distancia = "307.5 km",
                            Encerrada = false,
                            LembreteEnviado = false,
                            LembreteUrgenteEnviado = false,
                            Nome = "GP do Japão",
                            Numero = 4,
                            Pais = "🇯🇵",
                            PrazoQualify = new DateTime(2026, 3, 28, 3, 0, 0, 0, DateTimeKind.Utc),
                            Recordista = "Lewis Hamilton",
                            Sprint = false,
                            TempoRecord = "1:30.983",
                            TreinoLivre1 = new DateTime(2026, 3, 26, 3, 30, 0, 0, DateTimeKind.Utc),
                            TreinoLivre2 = new DateTime(2026, 3, 26, 7, 0, 0, 0, DateTimeKind.Utc),
                            TreinoLivre3 = new DateTime(2026, 3, 27, 3, 30, 0, 0, DateTimeKind.Utc),
                            Voltas = 53
                        },
                        new
                        {
                            Id = 5,
                            AnoRecord = 2005,
                            Cidade = "Sakhir",
                            Circuito = "Sakhir",
                            CircuitoComprimento = "5.412 km",
                            CircuitoSvg = "<svg viewBox=\"0 0 300 200\" fill=\"none\"><path d=\"M70 180 L70 140 Q70 120 90 110 L130 90 Q150 80 150 60 Q150 40 130 35 L90 30 Q70 30 60 45 L50 70 Q45 90 60 100 L100 120 Q120 130 120 150 L120 170 Q120 185 140 185 L200 180 Q230 175 250 150 L260 120 Q265 90 250 70 L230 50 Q210 35 190 40 L170 50\" stroke=\"white\" stroke-width=\"8\" stroke-linejoin=\"round\" stroke-linecap=\"round\"/><circle cx=\"70\" cy=\"180\" r=\"6\" fill=\"#E8001A\"/></svg>",
                            CircuitoTipo = "Circuito permanente (iluminado)",
                            Classificacao = new DateTime(2026, 4, 10, 16, 0, 0, 0, DateTimeKind.Utc),
                            DataCorrida = new DateTime(2026, 4, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Distancia = "308.2 km",
                            Encerrada = false,
                            LembreteEnviado = false,
                            LembreteUrgenteEnviado = false,
                            Nome = "GP do Bahrein",
                            Numero = 5,
                            Pais = "🇧🇭",
                            PrazoQualify = new DateTime(2026, 4, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Recordista = "Pedro de la Rosa",
                            Sprint = false,
                            TempoRecord = "1:30.252",
                            TreinoLivre1 = new DateTime(2026, 4, 9, 12, 30, 0, 0, DateTimeKind.Utc),
                            TreinoLivre2 = new DateTime(2026, 4, 9, 16, 0, 0, 0, DateTimeKind.Utc),
                            TreinoLivre3 = new DateTime(2026, 4, 10, 12, 30, 0, 0, DateTimeKind.Utc),
                            Voltas = 57
                        },
                        new
                        {
                            Id = 6,
                            AnoRecord = 2023,
                            Cidade = "Jeddah",
                            Circuito = "Jeddah",
                            CircuitoComprimento = "6.174 km",
                            CircuitoSvg = "<svg viewBox=\"0 0 300 200\" fill=\"none\"><path d=\"M40 190 L40 140 Q40 110 55 90 Q70 70 90 65 L140 55 Q165 50 175 35 Q185 20 210 20 L250 25 Q275 30 280 55 L280 100 Q280 130 260 150 Q240 170 210 175 L160 180 Q130 180 115 165 Q100 150 85 155 L60 170 Q45 180 40 190 Z\" stroke=\"white\" stroke-width=\"8\" stroke-linejoin=\"round\" stroke-linecap=\"round\"/><circle cx=\"40\" cy=\"190\" r=\"6\" fill=\"#E8001A\"/></svg>",
                            CircuitoTipo = "Circuito de rua",
                            Classificacao = new DateTime(2026, 4, 17, 18, 0, 0, 0, DateTimeKind.Utc),
                            DataCorrida = new DateTime(2026, 4, 18, 14, 0, 0, 0, DateTimeKind.Utc),
                            Distancia = "308.5 km",
                            Encerrada = false,
                            LembreteEnviado = false,
                            LembreteUrgenteEnviado = false,
                            Nome = "GP da Arábia Saudita",
                            Numero = 6,
                            Pais = "🇸🇦",
                            PrazoQualify = new DateTime(2026, 4, 18, 14, 0, 0, 0, DateTimeKind.Utc),
                            Recordista = "Sergio Perez",
                            Sprint = false,
                            TempoRecord = "1:30.734",
                            TreinoLivre1 = new DateTime(2026, 4, 16, 14, 30, 0, 0, DateTimeKind.Utc),
                            TreinoLivre2 = new DateTime(2026, 4, 16, 18, 0, 0, 0, DateTimeKind.Utc),
                            TreinoLivre3 = new DateTime(2026, 4, 17, 14, 30, 0, 0, DateTimeKind.Utc),
                            Voltas = 50
                        },
                        new
                        {
                            Id = 7,
                            AnoRecord = 2023,
                            Cidade = "Miami",
                            Circuito = "Miami",
                            CircuitoComprimento = "5.412 km",
                            CircuitoSvg = "<svg viewBox=\"0 0 300 200\" fill=\"none\"><path d=\"M50 170 L50 50 Q50 30 70 30 L240 30 Q260 30 260 50 L260 110 Q260 130 240 140 L150 145 Q130 145 125 160 Q120 175 100 180 L70 180 Q50 180 50 170 Z\" stroke=\"white\" stroke-width=\"8\" stroke-linejoin=\"round\" stroke-linecap=\"round\"/><circle cx=\"50\" cy=\"170\" r=\"6\" fill=\"#E8001A\"/></svg>",
                            CircuitoTipo = "Circuito semi-permanente",
                            Classificacao = new DateTime(2026, 4, 30, 21, 30, 0, 0, DateTimeKind.Utc),
                            DataCorrida = new DateTime(2026, 5, 1, 17, 30, 0, 0, DateTimeKind.Utc),
                            Distancia = "97.4 km",
                            Encerrada = false,
                            LembreteEnviado = false,
                            LembreteUrgenteEnviado = false,
                            Nome = "Sprint de Miami",
                            Numero = 7,
                            Pais = "🇺🇸",
                            PrazoQualify = new DateTime(2026, 5, 1, 17, 30, 0, 0, DateTimeKind.Utc),
                            Recordista = "Max Verstappen",
                            Sprint = true,
                            TempoRecord = "1:27.274",
                            TreinoLivre1 = new DateTime(2026, 4, 30, 18, 0, 0, 0, DateTimeKind.Utc),
                            Voltas = 18
                        },
                        new
                        {
                            Id = 8,
                            AnoRecord = 2023,
                            Cidade = "Miami",
                            Circuito = "Miami",
                            CircuitoComprimento = "5.412 km",
                            CircuitoSvg = "<svg viewBox=\"0 0 300 200\" fill=\"none\"><path d=\"M50 170 L50 50 Q50 30 70 30 L240 30 Q260 30 260 50 L260 110 Q260 130 240 140 L150 145 Q130 145 125 160 Q120 175 100 180 L70 180 Q50 180 50 170 Z\" stroke=\"white\" stroke-width=\"8\" stroke-linejoin=\"round\" stroke-linecap=\"round\"/><circle cx=\"50\" cy=\"170\" r=\"6\" fill=\"#E8001A\"/></svg>",
                            CircuitoTipo = "Circuito semi-permanente",
                            Classificacao = new DateTime(2026, 5, 1, 21, 30, 0, 0, DateTimeKind.Utc),
                            DataCorrida = new DateTime(2026, 5, 2, 17, 0, 0, 0, DateTimeKind.Utc),
                            Distancia = "308.3 km",
                            Encerrada = false,
                            LembreteEnviado = false,
                            LembreteUrgenteEnviado = false,
                            Nome = "GP de Miami",
                            Numero = 8,
                            Pais = "🇺🇸",
                            PrazoQualify = new DateTime(2026, 5, 2, 17, 0, 0, 0, DateTimeKind.Utc),
                            Recordista = "Max Verstappen",
                            Sprint = false,
                            TempoRecord = "1:27.274",
                            Voltas = 57
                        },
                        new
                        {
                            Id = 9,
                            AnoRecord = 2019,
                            Cidade = "Montreal",
                            Circuito = "Montreal",
                            CircuitoComprimento = "4.361 km",
                            CircuitoSvg = "<svg viewBox=\"0 0 300 200\" fill=\"none\"><path d=\"M60 180 L50 120 Q45 90 60 70 L100 40 Q120 25 150 25 L200 30 Q230 35 245 55 Q260 80 250 110 L230 140 Q215 160 190 170 L150 180 Q120 185 100 170 Q85 155 90 135 L100 110 Q110 90 130 85\" stroke=\"white\" stroke-width=\"8\" stroke-linejoin=\"round\" stroke-linecap=\"round\"/><circle cx=\"60\" cy=\"180\" r=\"6\" fill=\"#E8001A\"/></svg>",
                            CircuitoTipo = "Circuito semi-permanente",
                            Classificacao = new DateTime(2026, 5, 21, 21, 30, 0, 0, DateTimeKind.Utc),
                            DataCorrida = new DateTime(2026, 5, 22, 17, 30, 0, 0, DateTimeKind.Utc),
                            Distancia = "100.3 km",
                            Encerrada = false,
                            LembreteEnviado = false,
                            LembreteUrgenteEnviado = false,
                            Nome = "Sprint do Canadá",
                            Numero = 9,
                            Pais = "🇨🇦",
                            PrazoQualify = new DateTime(2026, 5, 22, 17, 30, 0, 0, DateTimeKind.Utc),
                            Recordista = "Valtteri Bottas",
                            Sprint = true,
                            TempoRecord = "1:13.078",
                            TreinoLivre1 = new DateTime(2026, 5, 21, 18, 0, 0, 0, DateTimeKind.Utc),
                            Voltas = 23
                        },
                        new
                        {
                            Id = 10,
                            AnoRecord = 2019,
                            Cidade = "Montreal",
                            Circuito = "Montreal",
                            CircuitoComprimento = "4.361 km",
                            CircuitoSvg = "<svg viewBox=\"0 0 300 200\" fill=\"none\"><path d=\"M60 180 L50 120 Q45 90 60 70 L100 40 Q120 25 150 25 L200 30 Q230 35 245 55 Q260 80 250 110 L230 140 Q215 160 190 170 L150 180 Q120 185 100 170 Q85 155 90 135 L100 110 Q110 90 130 85\" stroke=\"white\" stroke-width=\"8\" stroke-linejoin=\"round\" stroke-linecap=\"round\"/><circle cx=\"60\" cy=\"180\" r=\"6\" fill=\"#E8001A\"/></svg>",
                            CircuitoTipo = "Circuito semi-permanente",
                            Classificacao = new DateTime(2026, 5, 22, 21, 30, 0, 0, DateTimeKind.Utc),
                            DataCorrida = new DateTime(2026, 5, 23, 17, 0, 0, 0, DateTimeKind.Utc),
                            Distancia = "305.3 km",
                            Encerrada = false,
                            LembreteEnviado = false,
                            LembreteUrgenteEnviado = false,
                            Nome = "GP do Canadá",
                            Numero = 10,
                            Pais = "🇨🇦",
                            PrazoQualify = new DateTime(2026, 5, 23, 17, 0, 0, 0, DateTimeKind.Utc),
                            Recordista = "Valtteri Bottas",
                            Sprint = false,
                            TempoRecord = "1:13.078",
                            Voltas = 70
                        },
                        new
                        {
                            Id = 11,
                            AnoRecord = 2021,
                            Cidade = "Monte Carlo",
                            Circuito = "Monte Carlo",
                            CircuitoComprimento = "3.337 km",
                            CircuitoSvg = "<svg viewBox=\"0 0 300 200\" fill=\"none\"><path d=\"M80 180 L60 150 Q40 120 50 90 Q60 60 90 50 L130 40 Q155 35 165 55 Q175 75 160 90 L140 105 Q125 115 130 135 Q135 155 160 160 L200 155 Q230 145 245 120 Q260 95 250 70 L235 50 Q220 35 195 35\" stroke=\"white\" stroke-width=\"8\" stroke-linejoin=\"round\" stroke-linecap=\"round\"/><circle cx=\"80\" cy=\"180\" r=\"6\" fill=\"#E8001A\"/></svg>",
                            CircuitoTipo = "Circuito de rua",
                            Classificacao = new DateTime(2026, 6, 5, 15, 0, 0, 0, DateTimeKind.Utc),
                            DataCorrida = new DateTime(2026, 6, 6, 11, 0, 0, 0, DateTimeKind.Utc),
                            Distancia = "260.3 km",
                            Encerrada = false,
                            LembreteEnviado = false,
                            LembreteUrgenteEnviado = false,
                            Nome = "GP de Mônaco",
                            Numero = 11,
                            Pais = "🇲🇨",
                            PrazoQualify = new DateTime(2026, 6, 6, 11, 0, 0, 0, DateTimeKind.Utc),
                            Recordista = "Charles Leclerc",
                            Sprint = false,
                            TempoRecord = "1:12.909",
                            TreinoLivre1 = new DateTime(2026, 6, 4, 11, 30, 0, 0, DateTimeKind.Utc),
                            TreinoLivre2 = new DateTime(2026, 6, 4, 15, 0, 0, 0, DateTimeKind.Utc),
                            TreinoLivre3 = new DateTime(2026, 6, 5, 11, 30, 0, 0, DateTimeKind.Utc),
                            Voltas = 78
                        },
                        new
                        {
                            Id = 12,
                            AnoRecord = 2023,
                            Cidade = "Barcelona",
                            Circuito = "Catalunia",
                            CircuitoComprimento = "4.657 km",
                            CircuitoSvg = "<svg viewBox=\"0 0 300 200\" fill=\"none\"><path d=\"M50 160 L50 80 Q50 50 80 40 L200 30 Q240 28 260 50 Q280 75 270 100 L250 130 Q235 150 210 155 L160 160 Q140 160 130 145 Q120 130 100 135 L70 150 Q55 158 50 160 Z\" stroke=\"white\" stroke-width=\"8\" stroke-linejoin=\"round\" stroke-linecap=\"round\"/><circle cx=\"50\" cy=\"160\" r=\"6\" fill=\"#E8001A\"/></svg>",
                            CircuitoTipo = "Circuito permanente",
                            Classificacao = new DateTime(2026, 6, 12, 15, 0, 0, 0, DateTimeKind.Utc),
                            DataCorrida = new DateTime(2026, 6, 13, 11, 0, 0, 0, DateTimeKind.Utc),
                            Distancia = "307.3 km",
                            Encerrada = false,
                            LembreteEnviado = false,
                            LembreteUrgenteEnviado = false,
                            Nome = "GP de Barcelona",
                            Numero = 12,
                            Pais = "🇪🇸",
                            PrazoQualify = new DateTime(2026, 6, 13, 11, 0, 0, 0, DateTimeKind.Utc),
                            Recordista = "Max Verstappen",
                            Sprint = false,
                            TempoRecord = "1:16.330",
                            TreinoLivre1 = new DateTime(2026, 6, 11, 11, 30, 0, 0, DateTimeKind.Utc),
                            TreinoLivre2 = new DateTime(2026, 6, 11, 15, 0, 0, 0, DateTimeKind.Utc),
                            TreinoLivre3 = new DateTime(2026, 6, 12, 11, 30, 0, 0, DateTimeKind.Utc),
                            Voltas = 66
                        },
                        new
                        {
                            Id = 13,
                            AnoRecord = 2020,
                            Cidade = "Spielberg",
                            Circuito = "Red Bull Ring",
                            CircuitoComprimento = "4.318 km",
                            CircuitoSvg = "<svg viewBox=\"0 0 300 200\" fill=\"none\"><path d=\"M80 180 L60 140 Q50 110 70 80 L120 40 Q145 20 175 30 L220 55 Q245 70 250 100 L245 140 Q240 165 210 175 L150 185 Q110 188 80 180 Z\" stroke=\"white\" stroke-width=\"8\" stroke-linejoin=\"round\" stroke-linecap=\"round\"/><circle cx=\"80\" cy=\"180\" r=\"6\" fill=\"#E8001A\"/></svg>",
                            CircuitoTipo = "Circuito permanente",
                            Classificacao = new DateTime(2026, 6, 26, 15, 0, 0, 0, DateTimeKind.Utc),
                            DataCorrida = new DateTime(2026, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Distancia = "306.5 km",
                            Encerrada = false,
                            LembreteEnviado = false,
                            LembreteUrgenteEnviado = false,
                            Nome = "GP da Áustria",
                            Numero = 13,
                            Pais = "🇦🇹",
                            PrazoQualify = new DateTime(2026, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Recordista = "Carlos Sainz",
                            Sprint = false,
                            TempoRecord = "1:05.619",
                            TreinoLivre1 = new DateTime(2026, 6, 25, 11, 30, 0, 0, DateTimeKind.Utc),
                            TreinoLivre2 = new DateTime(2026, 6, 25, 15, 0, 0, 0, DateTimeKind.Utc),
                            TreinoLivre3 = new DateTime(2026, 6, 26, 11, 30, 0, 0, DateTimeKind.Utc),
                            Voltas = 71
                        },
                        new
                        {
                            Id = 14,
                            AnoRecord = 2020,
                            Cidade = "Silverstone",
                            Circuito = "Silverstone",
                            CircuitoComprimento = "5.891 km",
                            CircuitoSvg = "<svg viewBox=\"0 0 300 200\" fill=\"none\"><path d=\"M60 170 L40 130 Q25 100 45 70 Q65 45 100 35 L150 25 Q190 20 220 40 Q245 55 255 80 L260 110 Q262 140 240 160 Q215 178 180 180 L140 175 Q115 168 105 145 Q95 125 110 110 Q130 95 150 105 Q165 115 155 135\" stroke=\"white\" stroke-width=\"8\" stroke-linejoin=\"round\" stroke-linecap=\"round\"/><circle cx=\"60\" cy=\"170\" r=\"6\" fill=\"#E8001A\"/></svg>",
                            CircuitoTipo = "Circuito permanente",
                            Classificacao = new DateTime(2026, 7, 2, 16, 30, 0, 0, DateTimeKind.Utc),
                            DataCorrida = new DateTime(2026, 7, 3, 12, 30, 0, 0, DateTimeKind.Utc),
                            Distancia = "100.1 km",
                            Encerrada = false,
                            LembreteEnviado = false,
                            LembreteUrgenteEnviado = false,
                            Nome = "Sprint da Grã-Bretanha",
                            Numero = 14,
                            Pais = "🇬🇧",
                            PrazoQualify = new DateTime(2026, 7, 3, 12, 30, 0, 0, DateTimeKind.Utc),
                            Recordista = "Lewis Hamilton",
                            Sprint = true,
                            TempoRecord = "1:24.303",
                            TreinoLivre1 = new DateTime(2026, 7, 2, 13, 0, 0, 0, DateTimeKind.Utc),
                            Voltas = 17
                        },
                        new
                        {
                            Id = 15,
                            AnoRecord = 2020,
                            Cidade = "Silverstone",
                            Circuito = "Silverstone",
                            CircuitoComprimento = "5.891 km",
                            CircuitoSvg = "<svg viewBox=\"0 0 300 200\" fill=\"none\"><path d=\"M60 170 L40 130 Q25 100 45 70 Q65 45 100 35 L150 25 Q190 20 220 40 Q245 55 255 80 L260 110 Q262 140 240 160 Q215 178 180 180 L140 175 Q115 168 105 145 Q95 125 110 110 Q130 95 150 105 Q165 115 155 135\" stroke=\"white\" stroke-width=\"8\" stroke-linejoin=\"round\" stroke-linecap=\"round\"/><circle cx=\"60\" cy=\"170\" r=\"6\" fill=\"#E8001A\"/></svg>",
                            CircuitoTipo = "Circuito permanente",
                            Classificacao = new DateTime(2026, 7, 3, 16, 30, 0, 0, DateTimeKind.Utc),
                            DataCorrida = new DateTime(2026, 7, 4, 12, 0, 0, 0, DateTimeKind.Utc),
                            Distancia = "306.2 km",
                            Encerrada = false,
                            LembreteEnviado = false,
                            LembreteUrgenteEnviado = false,
                            Nome = "GP da Grã-Bretanha",
                            Numero = 15,
                            Pais = "🇬🇧",
                            PrazoQualify = new DateTime(2026, 7, 4, 12, 0, 0, 0, DateTimeKind.Utc),
                            Recordista = "Lewis Hamilton",
                            Sprint = false,
                            TempoRecord = "1:24.303",
                            Voltas = 52
                        },
                        new
                        {
                            Id = 16,
                            AnoRecord = 2018,
                            Cidade = "Spa",
                            Circuito = "Spa-Francorchamps",
                            CircuitoComprimento = "7.004 km",
                            CircuitoSvg = "<svg viewBox=\"0 0 300 200\" fill=\"none\"><path d=\"M40 170 L30 130 Q20 100 35 70 Q50 40 85 30 L130 20 Q160 15 175 35 Q190 55 175 80 L155 110 Q140 135 155 155 Q170 175 200 170 L240 155 Q270 140 280 110 L285 70 Q285 40 260 25\" stroke=\"white\" stroke-width=\"8\" stroke-linejoin=\"round\" stroke-linecap=\"round\"/><circle cx=\"40\" cy=\"170\" r=\"6\" fill=\"#E8001A\"/></svg>",
                            CircuitoTipo = "Circuito permanente",
                            Classificacao = new DateTime(2026, 7, 17, 15, 0, 0, 0, DateTimeKind.Utc),
                            DataCorrida = new DateTime(2026, 7, 18, 11, 0, 0, 0, DateTimeKind.Utc),
                            Distancia = "308.1 km",
                            Encerrada = false,
                            LembreteEnviado = false,
                            LembreteUrgenteEnviado = false,
                            Nome = "GP da Bélgica",
                            Numero = 16,
                            Pais = "🇧🇪",
                            PrazoQualify = new DateTime(2026, 7, 18, 11, 0, 0, 0, DateTimeKind.Utc),
                            Recordista = "Valtteri Bottas",
                            Sprint = false,
                            TempoRecord = "1:46.286",
                            TreinoLivre1 = new DateTime(2026, 7, 16, 11, 30, 0, 0, DateTimeKind.Utc),
                            TreinoLivre2 = new DateTime(2026, 7, 16, 15, 0, 0, 0, DateTimeKind.Utc),
                            TreinoLivre3 = new DateTime(2026, 7, 17, 11, 30, 0, 0, DateTimeKind.Utc),
                            Voltas = 44
                        },
                        new
                        {
                            Id = 17,
                            AnoRecord = 2020,
                            Cidade = "Budapest",
                            Circuito = "Hungaroring",
                            CircuitoComprimento = "4.381 km",
                            CircuitoSvg = "<svg viewBox=\"0 0 300 200\" fill=\"none\"><path d=\"M70 180 L50 150 Q30 120 40 85 Q50 55 80 40 L130 25 Q170 15 200 35 Q225 50 230 80 L228 120 Q225 150 200 168 L160 180 Q130 188 110 175 Q90 160 95 135 Q100 115 120 110 Q145 105 155 120\" stroke=\"white\" stroke-width=\"8\" stroke-linejoin=\"round\" stroke-linecap=\"round\"/><circle cx=\"70\" cy=\"180\" r=\"6\" fill=\"#E8001A\"/></svg>",
                            CircuitoTipo = "Circuito permanente",
                            Classificacao = new DateTime(2026, 7, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            DataCorrida = new DateTime(2026, 7, 25, 11, 0, 0, 0, DateTimeKind.Utc),
                            Distancia = "306.6 km",
                            Encerrada = false,
                            LembreteEnviado = false,
                            LembreteUrgenteEnviado = false,
                            Nome = "GP da Hungria",
                            Numero = 17,
                            Pais = "🇭🇺",
                            PrazoQualify = new DateTime(2026, 7, 25, 11, 0, 0, 0, DateTimeKind.Utc),
                            Recordista = "Lewis Hamilton",
                            Sprint = false,
                            TempoRecord = "1:16.627",
                            TreinoLivre1 = new DateTime(2026, 7, 23, 11, 30, 0, 0, DateTimeKind.Utc),
                            TreinoLivre2 = new DateTime(2026, 7, 23, 15, 0, 0, 0, DateTimeKind.Utc),
                            TreinoLivre3 = new DateTime(2026, 7, 24, 11, 30, 0, 0, DateTimeKind.Utc),
                            Voltas = 70
                        },
                        new
                        {
                            Id = 18,
                            AnoRecord = 2021,
                            Cidade = "Zandvoort",
                            Circuito = "Zandvoort",
                            CircuitoComprimento = "4.259 km",
                            CircuitoSvg = "<svg viewBox=\"0 0 300 200\" fill=\"none\"><path d=\"M60 170 L45 130 Q30 90 50 55 Q75 25 120 20 L190 22 Q230 25 255 55 Q275 80 265 115 Q255 145 225 165 L170 180 Q130 188 100 175 Q75 160 80 130 Q85 110 110 105\" stroke=\"white\" stroke-width=\"8\" stroke-linejoin=\"round\" stroke-linecap=\"round\"/><circle cx=\"60\" cy=\"170\" r=\"6\" fill=\"#E8001A\"/></svg>",
                            CircuitoTipo = "Circuito permanente",
                            Classificacao = new DateTime(2026, 8, 20, 15, 30, 0, 0, DateTimeKind.Utc),
                            DataCorrida = new DateTime(2026, 8, 21, 11, 30, 0, 0, DateTimeKind.Utc),
                            Distancia = "102.2 km",
                            Encerrada = false,
                            LembreteEnviado = false,
                            LembreteUrgenteEnviado = false,
                            Nome = "Sprint da Holanda",
                            Numero = 18,
                            Pais = "🇳🇱",
                            PrazoQualify = new DateTime(2026, 8, 21, 11, 30, 0, 0, DateTimeKind.Utc),
                            Recordista = "Max Verstappen",
                            Sprint = true,
                            TempoRecord = "1:11.097",
                            TreinoLivre1 = new DateTime(2026, 8, 20, 12, 0, 0, 0, DateTimeKind.Utc),
                            Voltas = 24
                        },
                        new
                        {
                            Id = 19,
                            AnoRecord = 2021,
                            Cidade = "Zandvoort",
                            Circuito = "Zandvoort",
                            CircuitoComprimento = "4.259 km",
                            CircuitoSvg = "<svg viewBox=\"0 0 300 200\" fill=\"none\"><path d=\"M60 170 L45 130 Q30 90 50 55 Q75 25 120 20 L190 22 Q230 25 255 55 Q275 80 265 115 Q255 145 225 165 L170 180 Q130 188 100 175 Q75 160 80 130 Q85 110 110 105\" stroke=\"white\" stroke-width=\"8\" stroke-linejoin=\"round\" stroke-linecap=\"round\"/><circle cx=\"60\" cy=\"170\" r=\"6\" fill=\"#E8001A\"/></svg>",
                            CircuitoTipo = "Circuito permanente",
                            Classificacao = new DateTime(2026, 8, 21, 15, 30, 0, 0, DateTimeKind.Utc),
                            DataCorrida = new DateTime(2026, 8, 22, 11, 0, 0, 0, DateTimeKind.Utc),
                            Distancia = "306.6 km",
                            Encerrada = false,
                            LembreteEnviado = false,
                            LembreteUrgenteEnviado = false,
                            Nome = "GP da Holanda",
                            Numero = 19,
                            Pais = "🇳🇱",
                            PrazoQualify = new DateTime(2026, 8, 22, 11, 0, 0, 0, DateTimeKind.Utc),
                            Recordista = "Max Verstappen",
                            Sprint = false,
                            TempoRecord = "1:11.097",
                            Voltas = 72
                        },
                        new
                        {
                            Id = 20,
                            AnoRecord = 2004,
                            Cidade = "Monza",
                            Circuito = "Monza",
                            CircuitoComprimento = "5.793 km",
                            CircuitoSvg = "<svg viewBox=\"0 0 300 200\" fill=\"none\"><path d=\"M70 180 L60 100 Q55 60 80 35 L150 20 Q200 15 230 40 Q255 60 250 95 L240 140 Q230 170 195 180 L140 185 Q100 185 85 165 Q75 145 90 125 L120 100 Q140 85 165 90\" stroke=\"white\" stroke-width=\"8\" stroke-linejoin=\"round\" stroke-linecap=\"round\"/><circle cx=\"70\" cy=\"180\" r=\"6\" fill=\"#E8001A\"/></svg>",
                            CircuitoTipo = "Circuito permanente (alta velocidade)",
                            Classificacao = new DateTime(2026, 9, 4, 15, 0, 0, 0, DateTimeKind.Utc),
                            DataCorrida = new DateTime(2026, 9, 5, 11, 0, 0, 0, DateTimeKind.Utc),
                            Distancia = "306.7 km",
                            Encerrada = false,
                            LembreteEnviado = false,
                            LembreteUrgenteEnviado = false,
                            Nome = "GP da Itália",
                            Numero = 20,
                            Pais = "🇮🇹",
                            PrazoQualify = new DateTime(2026, 9, 5, 11, 0, 0, 0, DateTimeKind.Utc),
                            Recordista = "Rubens Barrichello",
                            Sprint = false,
                            TempoRecord = "1:21.046",
                            TreinoLivre1 = new DateTime(2026, 9, 3, 11, 30, 0, 0, DateTimeKind.Utc),
                            TreinoLivre2 = new DateTime(2026, 9, 3, 15, 0, 0, 0, DateTimeKind.Utc),
                            TreinoLivre3 = new DateTime(2026, 9, 4, 11, 30, 0, 0, DateTimeKind.Utc),
                            Voltas = 53
                        },
                        new
                        {
                            Id = 21,
                            AnoRecord = 2026,
                            Cidade = "Madri",
                            Circuito = "Madri",
                            CircuitoComprimento = "5.474 km",
                            CircuitoSvg = "<svg viewBox=\"0 0 300 200\" fill=\"none\"><path d=\"M50 170 L40 110 Q35 70 65 45 L120 25 Q160 15 200 30 Q235 45 250 75 L258 115 Q262 150 235 172 L185 188 Q145 195 110 180 Q80 165 75 135 L78 105 Q82 85 105 80\" stroke=\"white\" stroke-width=\"8\" stroke-linejoin=\"round\" stroke-linecap=\"round\"/><circle cx=\"50\" cy=\"170\" r=\"6\" fill=\"#E8001A\"/></svg>",
                            CircuitoTipo = "Circuito semi-permanente",
                            Classificacao = new DateTime(2026, 9, 11, 15, 0, 0, 0, DateTimeKind.Utc),
                            DataCorrida = new DateTime(2026, 9, 12, 11, 0, 0, 0, DateTimeKind.Utc),
                            Distancia = "306.5 km",
                            Encerrada = false,
                            LembreteEnviado = false,
                            LembreteUrgenteEnviado = false,
                            Nome = "GP da Espanha",
                            Numero = 21,
                            Pais = "🇪🇸",
                            PrazoQualify = new DateTime(2026, 9, 12, 11, 0, 0, 0, DateTimeKind.Utc),
                            Recordista = "—",
                            Sprint = false,
                            TempoRecord = "—",
                            TreinoLivre1 = new DateTime(2026, 9, 10, 11, 30, 0, 0, DateTimeKind.Utc),
                            TreinoLivre2 = new DateTime(2026, 9, 10, 15, 0, 0, 0, DateTimeKind.Utc),
                            TreinoLivre3 = new DateTime(2026, 9, 11, 11, 30, 0, 0, DateTimeKind.Utc),
                            Voltas = 56
                        },
                        new
                        {
                            Id = 22,
                            AnoRecord = 2019,
                            Cidade = "Baku",
                            Circuito = "Baku",
                            CircuitoComprimento = "6.003 km",
                            CircuitoSvg = "<svg viewBox=\"0 0 300 200\" fill=\"none\"><path d=\"M50 190 L50 60 Q50 30 80 25 L120 20 Q150 18 160 40 L165 80 Q165 110 140 120 L100 130 Q75 135 75 155 L80 175 Q90 190 120 188 L220 180 Q260 175 275 150 L280 100 Q280 60 260 40\" stroke=\"white\" stroke-width=\"8\" stroke-linejoin=\"round\" stroke-linecap=\"round\"/><circle cx=\"50\" cy=\"190\" r=\"6\" fill=\"#E8001A\"/></svg>",
                            CircuitoTipo = "Circuito de rua",
                            Classificacao = new DateTime(2026, 9, 24, 13, 0, 0, 0, DateTimeKind.Utc),
                            DataCorrida = new DateTime(2026, 9, 25, 9, 0, 0, 0, DateTimeKind.Utc),
                            Distancia = "306.0 km",
                            Encerrada = false,
                            LembreteEnviado = false,
                            LembreteUrgenteEnviado = false,
                            Nome = "GP do Azerbaijão",
                            Numero = 22,
                            Pais = "🇦🇿",
                            PrazoQualify = new DateTime(2026, 9, 25, 9, 0, 0, 0, DateTimeKind.Utc),
                            Recordista = "Charles Leclerc",
                            Sprint = false,
                            TempoRecord = "1:43.009",
                            TreinoLivre1 = new DateTime(2026, 9, 23, 9, 30, 0, 0, DateTimeKind.Utc),
                            TreinoLivre2 = new DateTime(2026, 9, 23, 13, 0, 0, 0, DateTimeKind.Utc),
                            TreinoLivre3 = new DateTime(2026, 9, 24, 9, 30, 0, 0, DateTimeKind.Utc),
                            Voltas = 51
                        },
                        new
                        {
                            Id = 23,
                            AnoRecord = 2023,
                            Cidade = "Singapura",
                            Circuito = "Marina Bay",
                            CircuitoComprimento = "4.940 km",
                            CircuitoSvg = "<svg viewBox=\"0 0 300 200\" fill=\"none\"><path d=\"M60 180 L40 140 Q25 110 40 80 Q55 55 85 45 L130 35 Q160 30 180 45 Q200 60 195 85 L185 110 Q175 130 190 148 Q205 165 235 160 L260 150 Q280 135 278 110 L272 75 Q265 50 240 38 L200 28\" stroke=\"white\" stroke-width=\"8\" stroke-linejoin=\"round\" stroke-linecap=\"round\"/><circle cx=\"60\" cy=\"180\" r=\"6\" fill=\"#E8001A\"/></svg>",
                            CircuitoTipo = "Circuito de rua (noturno)",
                            Classificacao = new DateTime(2026, 10, 8, 13, 30, 0, 0, DateTimeKind.Utc),
                            DataCorrida = new DateTime(2026, 10, 9, 9, 30, 0, 0, DateTimeKind.Utc),
                            Distancia = "103.7 km",
                            Encerrada = false,
                            LembreteEnviado = false,
                            LembreteUrgenteEnviado = false,
                            Nome = "Sprint de Singapura",
                            Numero = 23,
                            Pais = "🇸🇬",
                            PrazoQualify = new DateTime(2026, 10, 9, 9, 30, 0, 0, DateTimeKind.Utc),
                            Recordista = "Lewis Hamilton",
                            Sprint = true,
                            TempoRecord = "1:35.867",
                            TreinoLivre1 = new DateTime(2026, 10, 8, 10, 0, 0, 0, DateTimeKind.Utc),
                            Voltas = 21
                        },
                        new
                        {
                            Id = 24,
                            AnoRecord = 2023,
                            Cidade = "Singapura",
                            Circuito = "Marina Bay",
                            CircuitoComprimento = "4.940 km",
                            CircuitoSvg = "<svg viewBox=\"0 0 300 200\" fill=\"none\"><path d=\"M60 180 L40 140 Q25 110 40 80 Q55 55 85 45 L130 35 Q160 30 180 45 Q200 60 195 85 L185 110 Q175 130 190 148 Q205 165 235 160 L260 150 Q280 135 278 110 L272 75 Q265 50 240 38 L200 28\" stroke=\"white\" stroke-width=\"8\" stroke-linejoin=\"round\" stroke-linecap=\"round\"/><circle cx=\"60\" cy=\"180\" r=\"6\" fill=\"#E8001A\"/></svg>",
                            CircuitoTipo = "Circuito de rua (noturno)",
                            Classificacao = new DateTime(2026, 10, 9, 14, 30, 0, 0, DateTimeKind.Utc),
                            DataCorrida = new DateTime(2026, 10, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            Distancia = "306.1 km",
                            Encerrada = false,
                            LembreteEnviado = false,
                            LembreteUrgenteEnviado = false,
                            Nome = "GP de Singapura",
                            Numero = 24,
                            Pais = "🇸🇬",
                            PrazoQualify = new DateTime(2026, 10, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            Recordista = "Lewis Hamilton",
                            Sprint = false,
                            TempoRecord = "1:35.867",
                            Voltas = 62
                        },
                        new
                        {
                            Id = 25,
                            AnoRecord = 2023,
                            Cidade = "Austin",
                            Circuito = "Austin",
                            CircuitoComprimento = "5.513 km",
                            CircuitoSvg = "<svg viewBox=\"0 0 300 200\" fill=\"none\"><path d=\"M60 180 L50 140 Q40 110 55 80 Q70 55 100 40 L140 25 Q170 18 195 30 Q215 40 210 65 Q205 85 185 90 Q165 95 170 115 Q175 135 200 140 L240 135 Q265 125 272 100 L275 65 Q275 35 255 22\" stroke=\"white\" stroke-width=\"8\" stroke-linejoin=\"round\" stroke-linecap=\"round\"/><circle cx=\"60\" cy=\"180\" r=\"6\" fill=\"#E8001A\"/></svg>",
                            CircuitoTipo = "Circuito permanente",
                            Classificacao = new DateTime(2026, 10, 23, 22, 0, 0, 0, DateTimeKind.Utc),
                            DataCorrida = new DateTime(2026, 10, 24, 18, 0, 0, 0, DateTimeKind.Utc),
                            Distancia = "308.4 km",
                            Encerrada = false,
                            LembreteEnviado = false,
                            LembreteUrgenteEnviado = false,
                            Nome = "GP dos EUA",
                            Numero = 25,
                            Pais = "🇺🇸",
                            PrazoQualify = new DateTime(2026, 10, 24, 18, 0, 0, 0, DateTimeKind.Utc),
                            Recordista = "Charles Leclerc",
                            Sprint = false,
                            TempoRecord = "1:36.169",
                            TreinoLivre1 = new DateTime(2026, 10, 22, 18, 30, 0, 0, DateTimeKind.Utc),
                            TreinoLivre2 = new DateTime(2026, 10, 22, 22, 0, 0, 0, DateTimeKind.Utc),
                            TreinoLivre3 = new DateTime(2026, 10, 23, 18, 30, 0, 0, DateTimeKind.Utc),
                            Voltas = 56
                        },
                        new
                        {
                            Id = 26,
                            AnoRecord = 2021,
                            Cidade = "Cidade do México",
                            Circuito = "Cidade do México",
                            CircuitoComprimento = "4.304 km",
                            CircuitoSvg = "<svg viewBox=\"0 0 300 200\" fill=\"none\"><path d=\"M70 180 L60 130 Q55 90 80 60 L130 30 Q165 15 200 30 L240 55 Q265 75 260 110 L250 150 Q240 175 210 185 L160 190 Q120 190 95 170 Q80 155 85 130 L95 105 Q108 85 135 82 Q160 80 165 100 Q168 120 148 128\" stroke=\"white\" stroke-width=\"8\" stroke-linejoin=\"round\" stroke-linecap=\"round\"/><circle cx=\"70\" cy=\"180\" r=\"6\" fill=\"#E8001A\"/></svg>",
                            CircuitoTipo = "Circuito permanente (alta altitude)",
                            Classificacao = new DateTime(2026, 10, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            DataCorrida = new DateTime(2026, 10, 31, 18, 0, 0, 0, DateTimeKind.Utc),
                            Distancia = "305.4 km",
                            Encerrada = false,
                            LembreteEnviado = false,
                            LembreteUrgenteEnviado = false,
                            Nome = "GP do México",
                            Numero = 26,
                            Pais = "🇲🇽",
                            PrazoQualify = new DateTime(2026, 10, 31, 18, 0, 0, 0, DateTimeKind.Utc),
                            Recordista = "Valtteri Bottas",
                            Sprint = false,
                            TempoRecord = "1:17.774",
                            TreinoLivre1 = new DateTime(2026, 10, 29, 18, 30, 0, 0, DateTimeKind.Utc),
                            TreinoLivre2 = new DateTime(2026, 10, 29, 22, 0, 0, 0, DateTimeKind.Utc),
                            TreinoLivre3 = new DateTime(2026, 10, 30, 18, 30, 0, 0, DateTimeKind.Utc),
                            Voltas = 71
                        },
                        new
                        {
                            Id = 27,
                            AnoRecord = 2018,
                            Cidade = "São Paulo",
                            Circuito = "Interlagos",
                            CircuitoComprimento = "4.309 km",
                            CircuitoSvg = "<svg viewBox=\"0 0 300 200\" fill=\"none\"><path d=\"M80 180 L60 140 Q40 100 60 65 Q80 35 120 25 L180 20 Q225 20 250 50 Q270 75 260 110 L240 150 Q220 178 180 185 L130 185 Q95 182 80 160 Q70 140 85 120 Q105 100 130 105\" stroke=\"white\" stroke-width=\"8\" stroke-linejoin=\"round\" stroke-linecap=\"round\"/><circle cx=\"80\" cy=\"180\" r=\"6\" fill=\"#E8001A\"/></svg>",
                            CircuitoTipo = "Circuito permanente",
                            Classificacao = new DateTime(2026, 11, 6, 19, 0, 0, 0, DateTimeKind.Utc),
                            DataCorrida = new DateTime(2026, 11, 7, 15, 0, 0, 0, DateTimeKind.Utc),
                            Distancia = "305.9 km",
                            Encerrada = false,
                            LembreteEnviado = false,
                            LembreteUrgenteEnviado = false,
                            Nome = "GP do Brasil",
                            Numero = 27,
                            Pais = "🇧🇷",
                            PrazoQualify = new DateTime(2026, 11, 7, 15, 0, 0, 0, DateTimeKind.Utc),
                            Recordista = "Valtteri Bottas",
                            Sprint = false,
                            TempoRecord = "1:10.540",
                            TreinoLivre1 = new DateTime(2026, 11, 5, 15, 30, 0, 0, DateTimeKind.Utc),
                            TreinoLivre2 = new DateTime(2026, 11, 5, 19, 0, 0, 0, DateTimeKind.Utc),
                            TreinoLivre3 = new DateTime(2026, 11, 6, 15, 30, 0, 0, DateTimeKind.Utc),
                            Voltas = 71
                        },
                        new
                        {
                            Id = 28,
                            AnoRecord = 2023,
                            Cidade = "Las Vegas",
                            Circuito = "Las Vegas",
                            CircuitoComprimento = "6.201 km",
                            CircuitoSvg = "<svg viewBox=\"0 0 300 200\" fill=\"none\"><path d=\"M50 180 L50 40 Q50 20 70 20 L100 20 Q120 20 120 40 L120 130 Q120 155 145 155 L230 155 Q255 155 255 135 L255 60 Q255 40 275 40 L280 40 Q290 40 290 60 L290 180 Q290 195 270 195 L70 195 Q50 195 50 180 Z\" stroke=\"white\" stroke-width=\"8\" stroke-linejoin=\"round\" stroke-linecap=\"round\"/><circle cx=\"50\" cy=\"180\" r=\"6\" fill=\"#E8001A\"/></svg>",
                            CircuitoTipo = "Circuito de rua (noturno)",
                            Classificacao = new DateTime(2026, 11, 20, 5, 0, 0, 0, DateTimeKind.Utc),
                            DataCorrida = new DateTime(2026, 11, 21, 1, 0, 0, 0, DateTimeKind.Utc),
                            Distancia = "310.0 km",
                            Encerrada = false,
                            LembreteEnviado = false,
                            LembreteUrgenteEnviado = false,
                            Nome = "GP de Las Vegas",
                            Numero = 28,
                            Pais = "🇺🇸",
                            PrazoQualify = new DateTime(2026, 11, 21, 1, 0, 0, 0, DateTimeKind.Utc),
                            Recordista = "Max Verstappen",
                            Sprint = false,
                            TempoRecord = "1:35.490",
                            TreinoLivre1 = new DateTime(2026, 11, 19, 1, 30, 0, 0, DateTimeKind.Utc),
                            TreinoLivre2 = new DateTime(2026, 11, 19, 5, 0, 0, 0, DateTimeKind.Utc),
                            TreinoLivre3 = new DateTime(2026, 11, 20, 1, 30, 0, 0, DateTimeKind.Utc),
                            Voltas = 50
                        },
                        new
                        {
                            Id = 29,
                            AnoRecord = 2023,
                            Cidade = "Lusail",
                            Circuito = "Lusail",
                            CircuitoComprimento = "5.380 km",
                            CircuitoSvg = "<svg viewBox=\"0 0 300 200\" fill=\"none\"><path d=\"M60 180 L45 130 Q30 85 55 50 Q80 20 130 15 L200 18 Q245 22 268 55 Q285 85 275 120 L260 155 Q240 180 205 185 L150 188 Q110 188 85 170 Q65 152 72 125 Q80 100 110 95 Q140 92 150 110\" stroke=\"white\" stroke-width=\"8\" stroke-linejoin=\"round\" stroke-linecap=\"round\"/><circle cx=\"60\" cy=\"180\" r=\"6\" fill=\"#E8001A\"/></svg>",
                            CircuitoTipo = "Circuito permanente (noturno)",
                            Classificacao = new DateTime(2026, 11, 27, 19, 0, 0, 0, DateTimeKind.Utc),
                            DataCorrida = new DateTime(2026, 11, 28, 15, 0, 0, 0, DateTimeKind.Utc),
                            Distancia = "306.6 km",
                            Encerrada = false,
                            LembreteEnviado = false,
                            LembreteUrgenteEnviado = false,
                            Nome = "GP do Catar",
                            Numero = 29,
                            Pais = "🇶🇦",
                            PrazoQualify = new DateTime(2026, 11, 28, 15, 0, 0, 0, DateTimeKind.Utc),
                            Recordista = "Charles Leclerc",
                            Sprint = false,
                            TempoRecord = "1:24.319",
                            TreinoLivre1 = new DateTime(2026, 11, 26, 15, 30, 0, 0, DateTimeKind.Utc),
                            TreinoLivre2 = new DateTime(2026, 11, 26, 19, 0, 0, 0, DateTimeKind.Utc),
                            TreinoLivre3 = new DateTime(2026, 11, 27, 15, 30, 0, 0, DateTimeKind.Utc),
                            Voltas = 57
                        },
                        new
                        {
                            Id = 30,
                            AnoRecord = 2021,
                            Cidade = "Abu Dhabi",
                            Circuito = "Yas Marina",
                            CircuitoComprimento = "5.281 km",
                            CircuitoSvg = "<svg viewBox=\"0 0 300 200\" fill=\"none\"><path d=\"M60 180 L45 140 Q30 100 50 65 Q70 35 110 25 L170 20 Q215 18 245 40 Q270 60 272 95 L270 130 Q265 160 240 175 L200 185 Q165 190 140 178 Q120 165 115 140 Q110 115 130 100 Q150 88 175 95 L200 108 Q218 120 210 142\" stroke=\"white\" stroke-width=\"8\" stroke-linejoin=\"round\" stroke-linecap=\"round\"/><circle cx=\"60\" cy=\"180\" r=\"6\" fill=\"#E8001A\"/></svg>",
                            CircuitoTipo = "Circuito permanente",
                            Classificacao = new DateTime(2026, 12, 4, 15, 0, 0, 0, DateTimeKind.Utc),
                            DataCorrida = new DateTime(2026, 12, 5, 11, 0, 0, 0, DateTimeKind.Utc),
                            Distancia = "306.2 km",
                            Encerrada = false,
                            LembreteEnviado = false,
                            LembreteUrgenteEnviado = false,
                            Nome = "GP de Abu Dhabi",
                            Numero = 30,
                            Pais = "🇦🇪",
                            PrazoQualify = new DateTime(2026, 12, 5, 11, 0, 0, 0, DateTimeKind.Utc),
                            Recordista = "Max Verstappen",
                            Sprint = false,
                            TempoRecord = "1:26.103",
                            TreinoLivre1 = new DateTime(2026, 12, 3, 11, 30, 0, 0, DateTimeKind.Utc),
                            TreinoLivre2 = new DateTime(2026, 12, 3, 15, 0, 0, 0, DateTimeKind.Utc),
                            TreinoLivre3 = new DateTime(2026, 12, 4, 11, 30, 0, 0, DateTimeKind.Utc),
                            Voltas = 58
                        });
                });

            modelBuilder.Entity("F1Fast.API.Models.Palpite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("EnviadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EtapaId")
                        .HasColumnType("int");

                    b.Property<int>("MelhorVoltaId")
                        .HasColumnType("int");

                    b.Property<int>("PoleId")
                        .HasColumnType("int");

                    b.Property<int?>("PontosObtidos")
                        .HasColumnType("int");

                    b.Property<int>("Pos10Id")
                        .HasColumnType("int");

                    b.Property<int>("Pos1Id")
                        .HasColumnType("int");

                    b.Property<int>("Pos2Id")
                        .HasColumnType("int");

                    b.Property<int>("Pos3Id")
                        .HasColumnType("int");

                    b.Property<int>("Pos4Id")
                        .HasColumnType("int");

                    b.Property<int>("Pos5Id")
                        .HasColumnType("int");

                    b.Property<int>("Pos6Id")
                        .HasColumnType("int");

                    b.Property<int>("Pos7Id")
                        .HasColumnType("int");

                    b.Property<int>("Pos8Id")
                        .HasColumnType("int");

                    b.Property<int>("Pos9Id")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EtapaId");

                    b.HasIndex("UsuarioId", "EtapaId")
                        .IsUnique();

                    b.ToTable("Palpites");
                });

            modelBuilder.Entity("F1Fast.API.Models.Piloto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("EquipeId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipeId");

                    b.ToTable("Pilotos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            EquipeId = 1,
                            Nome = "Lando Norris",
                            Numero = 1
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            EquipeId = 2,
                            Nome = "Max Verstappen",
                            Numero = 3
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            EquipeId = 8,
                            Nome = "Gabriel Bortoleto",
                            Numero = 5
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            EquipeId = 2,
                            Nome = "Isack Hadjar",
                            Numero = 6
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            EquipeId = 7,
                            Nome = "Pierre Gasly",
                            Numero = 10
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            EquipeId = 11,
                            Nome = "Sergio Perez",
                            Numero = 11
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            EquipeId = 3,
                            Nome = "Kimi Antonelli",
                            Numero = 12
                        },
                        new
                        {
                            Id = 8,
                            Ativo = true,
                            EquipeId = 5,
                            Nome = "Fernando Alonso",
                            Numero = 14
                        },
                        new
                        {
                            Id = 9,
                            Ativo = true,
                            EquipeId = 4,
                            Nome = "Charles Leclerc",
                            Numero = 16
                        },
                        new
                        {
                            Id = 10,
                            Ativo = true,
                            EquipeId = 5,
                            Nome = "Lance Stroll",
                            Numero = 18
                        },
                        new
                        {
                            Id = 11,
                            Ativo = true,
                            EquipeId = 6,
                            Nome = "Alexander Albon",
                            Numero = 23
                        },
                        new
                        {
                            Id = 12,
                            Ativo = true,
                            EquipeId = 8,
                            Nome = "Nico Hülkenberg",
                            Numero = 27
                        },
                        new
                        {
                            Id = 13,
                            Ativo = true,
                            EquipeId = 10,
                            Nome = "Liam Lawson",
                            Numero = 30
                        },
                        new
                        {
                            Id = 14,
                            Ativo = true,
                            EquipeId = 9,
                            Nome = "Esteban Ocon",
                            Numero = 31
                        },
                        new
                        {
                            Id = 15,
                            Ativo = true,
                            EquipeId = 10,
                            Nome = "Arvid Lindblad",
                            Numero = 41
                        },
                        new
                        {
                            Id = 16,
                            Ativo = true,
                            EquipeId = 7,
                            Nome = "Franco Colapinto",
                            Numero = 43
                        },
                        new
                        {
                            Id = 17,
                            Ativo = true,
                            EquipeId = 4,
                            Nome = "Lewis Hamilton",
                            Numero = 44
                        },
                        new
                        {
                            Id = 18,
                            Ativo = true,
                            EquipeId = 6,
                            Nome = "Carlos Sainz",
                            Numero = 55
                        },
                        new
                        {
                            Id = 19,
                            Ativo = true,
                            EquipeId = 3,
                            Nome = "George Russell",
                            Numero = 63
                        },
                        new
                        {
                            Id = 20,
                            Ativo = true,
                            EquipeId = 11,
                            Nome = "Valtteri Bottas",
                            Numero = 77
                        },
                        new
                        {
                            Id = 21,
                            Ativo = true,
                            EquipeId = 1,
                            Nome = "Oscar Piastri",
                            Numero = 81
                        },
                        new
                        {
                            Id = 22,
                            Ativo = true,
                            EquipeId = 9,
                            Nome = "Oliver Bearman",
                            Numero = 87
                        });
                });

            modelBuilder.Entity("F1Fast.API.Models.Pontuacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AcertosExatos")
                        .HasColumnType("int");

                    b.Property<int>("AcertosPiloto")
                        .HasColumnType("int");

                    b.Property<int>("AcertosUmaPos")
                        .HasColumnType("int");

                    b.Property<bool>("AcertouMelhorVolta")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AcertouPole")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("EtapaId")
                        .HasColumnType("int");

                    b.Property<int>("Pontos")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EtapaId");

                    b.HasIndex("UsuarioId", "EtapaId")
                        .IsUnique();

                    b.ToTable("Pontuacoes");
                });

            modelBuilder.Entity("F1Fast.API.Models.Resultado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("EtapaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InseridoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MelhorVoltaId")
                        .HasColumnType("int");

                    b.Property<int>("PoleId")
                        .HasColumnType("int");

                    b.Property<int>("Pos10Id")
                        .HasColumnType("int");

                    b.Property<int>("Pos11Id")
                        .HasColumnType("int");

                    b.Property<int>("Pos1Id")
                        .HasColumnType("int");

                    b.Property<int>("Pos2Id")
                        .HasColumnType("int");

                    b.Property<int>("Pos3Id")
                        .HasColumnType("int");

                    b.Property<int>("Pos4Id")
                        .HasColumnType("int");

                    b.Property<int>("Pos5Id")
                        .HasColumnType("int");

                    b.Property<int>("Pos6Id")
                        .HasColumnType("int");

                    b.Property<int>("Pos7Id")
                        .HasColumnType("int");

                    b.Property<int>("Pos8Id")
                        .HasColumnType("int");

                    b.Property<int>("Pos9Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EtapaId")
                        .IsUnique();

                    b.ToTable("Resultados");
                });

            modelBuilder.Entity("F1Fast.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ResetToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("F1Fast.API.Models.Palpite", b =>
                {
                    b.HasOne("F1Fast.API.Models.Etapa", "Etapa")
                        .WithMany("Palpites")
                        .HasForeignKey("EtapaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("F1Fast.API.Models.Usuario", "Usuario")
                        .WithMany("Palpites")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etapa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("F1Fast.API.Models.Piloto", b =>
                {
                    b.HasOne("F1Fast.API.Models.Equipe", "Equipe")
                        .WithMany("Pilotos")
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipe");
                });

            modelBuilder.Entity("F1Fast.API.Models.Pontuacao", b =>
                {
                    b.HasOne("F1Fast.API.Models.Etapa", "Etapa")
                        .WithMany()
                        .HasForeignKey("EtapaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("F1Fast.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etapa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("F1Fast.API.Models.Resultado", b =>
                {
                    b.HasOne("F1Fast.API.Models.Etapa", "Etapa")
                        .WithOne("Resultado")
                        .HasForeignKey("F1Fast.API.Models.Resultado", "EtapaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etapa");
                });

            modelBuilder.Entity("F1Fast.API.Models.Equipe", b =>
                {
                    b.Navigation("Pilotos");
                });

            modelBuilder.Entity("F1Fast.API.Models.Etapa", b =>
                {
                    b.Navigation("Palpites");

                    b.Navigation("Resultado");
                });

            modelBuilder.Entity("F1Fast.API.Models.Usuario", b =>
                {
                    b.Navigation("Palpites");
                });
#pragma warning restore 612, 618
        }
    }
}
